import { User } from './types';

export const MOCK_ORGANISATION_USERS: User[] = [
  {
    id: 'USR-001',
    username: 'anjali.prasad',
    firstName: 'Anjali',
    lastName: 'Prasad',
    fullName: 'Anjali Prasad',
    email: 'anjali.prasad@servigen.io',
    phone: '+91 98765 43210',
    networkLogin: 'CORP\\anjali.p',
    defaultSite: 'Bangalore HQ',
    defaultOrganisation: 'ServiGen Global Tech',
    region: 'APAC',
    role: 'Administrator',
    status: 'Active',
    lastLogin: '2026-10-05 09:15 AM',
    department: 'IT Operations'
  },
  {
    id: 'USR-002',
    username: 'durgesh.k',
    firstName: 'Durgesh',
    lastName: 'Kumar',
    fullName: 'Durgesh Kumar',
    email: 'durgesh.k@servigen.io',
    phone: '+91 98765 43211',
    networkLogin: 'CORP\\durgesh.k',
    defaultSite: 'Bangalore HQ',
    defaultOrganisation: 'ServiGen Global Tech',
    region: 'APAC',
    role: 'Team Lead',
    status: 'Active',
    lastLogin: '2026-10-05 08:30 AM',
    department: 'Frontend Architecture'
  },
  {
    id: 'USR-003',
    username: 'nainesh.p',
    firstName: 'Nainesh',
    lastName: 'Patel',
    fullName: 'Nainesh Patel',
    email: 'nainesh.p@servigen.io',
    phone: '+91 98765 43212',
    networkLogin: 'CORP\\nainesh.p',
    defaultSite: 'Hyderabad Hub',
    defaultOrganisation: 'Halo AI Enterprise',
    region: 'APAC',
    role: 'System Manager',
    status: 'Active',
    lastLogin: '2026-10-05 10:00 AM',
    department: 'Backend & Integration'
  },
  {
    id: 'USR-004',
    username: 'taha.ali',
    firstName: 'Mohammad',
    lastName: 'Taha Ali',
    fullName: 'Mohammad Taha Ali',
    email: 'taha.ali@servigen.io',
    phone: '+91 98765 43213',
    networkLogin: 'CORP\\taha.a',
    defaultSite: 'London UK Branch',
    defaultOrganisation: 'Halo AI Europe',
    region: 'EMEA',
    role: 'Support Agent',
    status: 'Active',
    lastLogin: '2026-10-04 04:45 PM',
    department: 'Incidents & Analytics'
  },
  {
    id: 'USR-005',
    username: 'monalisa.p',
    firstName: 'Monalisa',
    lastName: 'Panda',
    fullName: 'Monalisa Panda',
    email: 'monalisa.p@servigen.io',
    phone: '+91 98765 43214',
    networkLogin: 'CORP\\monalisa.p',
    defaultSite: 'New York HQ',
    defaultOrganisation: 'Halo Americas Inc.',
    region: 'Americas',
    role: 'Support Agent',
    status: 'Active',
    lastLogin: '2026-10-05 07:50 AM',
    department: 'Project Management'
  },
  {
    id: 'USR-006',
    username: 'sarayu.v',
    firstName: 'Voona',
    lastName: 'Sarayu',
    fullName: 'Voona Sarayu',
    email: 'sarayu.v@servigen.io',
    phone: '+91 98765 43215',
    networkLogin: 'CORP\\sarayu.v',
    defaultSite: 'Frankfurt Tech Center',
    defaultOrganisation: 'Halo AI Europe',
    region: 'EMEA',
    role: 'End User',
    status: 'Inactive',
    lastLogin: '2026-09-20 02:15 PM',
    department: 'Services Catalogue'
  },
  {
    id: 'USR-007',
    username: 'aditya.singh',
    firstName: 'Aditya',
    lastName: 'Kumar Singh',
    fullName: 'Aditya Kumar Singh',
    email: 'aditya.singh@servigen.io',
    phone: '+91 98765 43216',
    networkLogin: 'CORP\\aditya.s',
    defaultSite: 'San Jose US Office',
    defaultOrganisation: 'Halo Americas Inc.',
    region: 'Americas',
    role: 'Support Agent',
    status: 'Active',
    lastLogin: '2026-10-05 09:05 AM',
    department: 'Approvals & Articles'
  },
  {
    id: 'USR-008',
    username: 'keerthana.m',
    firstName: 'Keerthana',
    lastName: 'M',
    fullName: 'Keerthana M',
    email: 'keerthana.m@servigen.io',
    phone: '+91 98765 43217',
    networkLogin: 'CORP\\keerthana.m',
    defaultSite: 'Bangalore HQ',
    defaultOrganisation: 'ServiGen Global Tech',
    region: 'APAC',
    role: 'Support Agent',
    status: 'Pending',
    lastLogin: 'Never',
    department: 'Service Desk'
  }
];
