export const INITIAL_PROJECTS = [
  {
    id: 1,
    name: 'ServiGen',
    description: 'Service management platform for managing IT workflows.',
    status: 'active',
    completion: 65,
    timeline: 'Sep 2026 - Oct 2026',
    timeSpent: '42 hrs',
    completedSubtasks: 8,
    totalSubtasks: 12,
  },
  {
    id: 2,
    name: 'Dashboard Modernization',
    description: 'Modernize the service management dashboard experience.',
    status: 'active',
    completion: 40,
    timeline: 'Sep 2026 - Nov 2026',
    timeSpent: '28 hrs',
    completedSubtasks: 5,
    totalSubtasks: 14,
  },
  {
    id: 3,
    name: 'Knowledge Base Upgrade',
    description: 'Improve knowledge management and article workflows.',
    status: 'completed',
    completion: 100,
    timeline: 'Aug 2026 - Sep 2026',
    timeSpent: '36 hrs',
    completedSubtasks: 10,
    totalSubtasks: 10,
  },
];